# Generated by Django 3.1.5 on 2021-01-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('mname', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 't_menu',
            },
        ),
    ]
